[package]
name = "token-factory"
version = "0.1.0"
edition = "2021"

[dependencies]
fluentbase-sdk = { workspace = true }
token-interfaces = { path = "../../interfaces" }
shared-types = { path = "../../shared-types" }

[lib]
crate-type = ["cdylib"]
