[package]
name = "shared-types"
version = "0.1.0"
edition = "2021"

[dependencies]
fluentbase-sdk = { git = "https://github.com/fluentlabs-xyz/fluentbase", tag = "v0.4.0-dev", default-features=false }

[lib]
crate-type = ["lib"]

[features]
default = ["std"]
std = ["fluentbase-sdk/std"]
wasm = []
